### ISSUE TITLE
Android is not compiling

### ISSUE THREAD

**Issue by SuhanKoh** [mCodex/react-native-redux-boilerplate#5]
When I tried to do
```react-native run-android```

It throw error about buildtool, then missing package in MainApplication/Activity.

**Comment by mCodex** [comment]
I've just merged the #6 :)

**Comment by jperniatera** [comment]
You should close the issue ? @mCodex =)

**Comment by josepernia91** [comment]
I think you could close the Issue now =P @mCodex
